name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  runs-on: macos-latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: {python-version: "3.7"}
    - name: Update pip
      run: python -m pip install -U 'pip==23.1.1'
    - name: Try to install .whl file
      run: python -m pip install ./macos_tag_test-0.42-0.editable-cp37-cp37m-macosx_12_0_x86_64.whl
    - name: List all installed packages
      run: python -m pip list
