name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: {python-version: "3.7"}
      - run: python -m pip install packaging
      - run: python -c 'from packaging.tags import sys_tags; print(next(sys_tags()))'
      - run: python -m pip install -U 'pip==23.1.1'
      - run: python -m pip list
      - run: python -m pip -vvv install ./macos_tag_test-0.42-0.editable-cp37-cp37m-macosx_12_0_x86_64.whl
      - run: python -m pip list
